#!/usr/bin/env python3
"""
setup_env.py - Interactive setup script for .env configuration
Run this script to quickly configure your OpenCode API key

Usage:
    python3 setup_env.py
"""

import os
import sys
from pathlib import Path

def get_godot_user_data_path():
    """Get the Godot user data directory path based on OS"""
    home = Path.home()
    
    if sys.platform == "win32":
        # Windows: %APPDATA%\Godot\app_userdata\<project>
        appdata = os.getenv("APPDATA")
        if appdata:
            return Path(appdata) / "Godot" / "app_userdata"
    elif sys.platform == "darwin":
        # macOS: ~/Library/Application Support/Godot/app_userdata/<project>
        return home / "Library" / "Application Support" / "Godot" / "app_userdata"
    else:
        # Linux: ~/.local/share/godot/app_userdata/<project>
        return home / ".local" / "share" / "godot" / "app_userdata"
    
    return None

def setup_env():
    """Interactive setup for .env file"""
    print("=" * 60)
    print("Educational Fantasy RPG - Configuration Setup")
    print("=" * 60)
    print()
    
    # Get Godot data path
    godot_path = get_godot_user_data_path()
    if not godot_path:
        print("❌ Could not determine Godot user data path")
        print("Please set up manually: SETUP_GUIDE.md")
        return False
    
    print(f"📁 Godot User Data Path: {godot_path}")
    print()
    
    # Find project folder
    project_name = input("Enter your project folder name (from Godot user data): ").strip()
    if not project_name:
        project_name = "Educational_Fantasy_RPG"
    
    env_dir = godot_path / project_name
    env_file = env_dir / ".env"
    
    print(f"📝 .env file will be created at: {env_file}")
    print()
    
    # Get API key
    print("🔑 OpenCode AI Configuration")
    print("   Get your API key from: https://opencode.ai/")
    print()
    api_key = input("Enter your OpenCode API key (sk-...): ").strip()
    
    if not api_key:
        print("❌ API key cannot be empty")
        return False
    
    if not api_key.startswith("sk-"):
        print("⚠️  Warning: API key should start with 'sk-'")
        confirm = input("Continue anyway? (y/n): ").strip().lower()
        if confirm != "y":
            return False
    
    # Optional: Custom API URL
    api_url = input("Enter API URL (press Enter for default): ").strip()
    if not api_url:
        api_url = "https://api.opencode.ai/v1/chat/completions"
    
    # Optional: Custom Model
    model = input("Enter model name (press Enter for default): ").strip()
    if not model:
        model = "typhoon-v1.5x-70b-instruct"
    
    print()
    print("=" * 60)
    print("Configuration Summary:")
    print("=" * 60)
    print(f"API URL: {api_url}")
    print(f"Model: {model}")
    print(f"API Key: {api_key[:10]}{'*' * 20}")
    print()
    
    # Create directory if needed
    env_dir.mkdir(parents=True, exist_ok=True)
    
    # Write .env file
    env_content = f"""# OpenCode AI Configuration
# Auto-generated by setup_env.py
# Do not commit this file to version control!

[llm]
api_key={api_key}
api_url={api_url}
model={model}
"""
    
    try:
        env_file.write_text(env_content)
        print(f"✅ Successfully created: {env_file}")
        print()
        print("🎮 You can now run the game in Godot!")
        return True
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")
        return False

if __name__ == "__main__":
    try:
        if setup_env():
            sys.exit(0)
        else:
            sys.exit(1)
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user")
        sys.exit(1)
